// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package local

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"internal"
)

type Link struct {
	pulumi.CustomResourceState

	Is_dir    pulumi.BoolOutput        `pulumi:"is_dir"`
	Linked    pulumi.BoolOutput        `pulumi:"linked"`
	Overwrite pulumi.BoolPtrOutput     `pulumi:"overwrite"`
	Recursive pulumi.BoolPtrOutput     `pulumi:"recursive"`
	Retain    pulumi.BoolPtrOutput     `pulumi:"retain"`
	Source    pulumi.StringOutput      `pulumi:"source"`
	Target    pulumi.StringOutput      `pulumi:"target"`
	Targets   pulumi.StringArrayOutput `pulumi:"targets"`
}

// NewLink registers a new resource with the given unique name, arguments, and options.
func NewLink(ctx *pulumi.Context,
	name string, args *LinkArgs, opts ...pulumi.ResourceOption) (*Link, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Source == nil {
		return nil, errors.New("invalid value for required argument 'Source'")
	}
	if args.Target == nil {
		return nil, errors.New("invalid value for required argument 'Target'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Link
	err := ctx.RegisterResource("pde:local:Link", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetLink gets an existing Link resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetLink(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *LinkState, opts ...pulumi.ResourceOption) (*Link, error) {
	var resource Link
	err := ctx.ReadResource("pde:local:Link", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Link resources.
type linkState struct {
}

type LinkState struct {
}

func (LinkState) ElementType() reflect.Type {
	return reflect.TypeOf((*linkState)(nil)).Elem()
}

type linkArgs struct {
	Overwrite *bool  `pulumi:"overwrite"`
	Recursive *bool  `pulumi:"recursive"`
	Retain    *bool  `pulumi:"retain"`
	Source    string `pulumi:"source"`
	Target    string `pulumi:"target"`
}

// The set of arguments for constructing a Link resource.
type LinkArgs struct {
	Overwrite pulumi.BoolPtrInput
	Recursive pulumi.BoolPtrInput
	Retain    pulumi.BoolPtrInput
	Source    pulumi.StringInput
	Target    pulumi.StringInput
}

func (LinkArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*linkArgs)(nil)).Elem()
}

type LinkInput interface {
	pulumi.Input

	ToLinkOutput() LinkOutput
	ToLinkOutputWithContext(ctx context.Context) LinkOutput
}

func (*Link) ElementType() reflect.Type {
	return reflect.TypeOf((**Link)(nil)).Elem()
}

func (i *Link) ToLinkOutput() LinkOutput {
	return i.ToLinkOutputWithContext(context.Background())
}

func (i *Link) ToLinkOutputWithContext(ctx context.Context) LinkOutput {
	return pulumi.ToOutputWithContext(ctx, i).(LinkOutput)
}

type LinkOutput struct{ *pulumi.OutputState }

func (LinkOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Link)(nil)).Elem()
}

func (o LinkOutput) ToLinkOutput() LinkOutput {
	return o
}

func (o LinkOutput) ToLinkOutputWithContext(ctx context.Context) LinkOutput {
	return o
}

func (o LinkOutput) Is_dir() pulumi.BoolOutput {
	return o.ApplyT(func(v *Link) pulumi.BoolOutput { return v.Is_dir }).(pulumi.BoolOutput)
}

func (o LinkOutput) Linked() pulumi.BoolOutput {
	return o.ApplyT(func(v *Link) pulumi.BoolOutput { return v.Linked }).(pulumi.BoolOutput)
}

func (o LinkOutput) Overwrite() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Link) pulumi.BoolPtrOutput { return v.Overwrite }).(pulumi.BoolPtrOutput)
}

func (o LinkOutput) Recursive() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Link) pulumi.BoolPtrOutput { return v.Recursive }).(pulumi.BoolPtrOutput)
}

func (o LinkOutput) Retain() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Link) pulumi.BoolPtrOutput { return v.Retain }).(pulumi.BoolPtrOutput)
}

func (o LinkOutput) Source() pulumi.StringOutput {
	return o.ApplyT(func(v *Link) pulumi.StringOutput { return v.Source }).(pulumi.StringOutput)
}

func (o LinkOutput) Target() pulumi.StringOutput {
	return o.ApplyT(func(v *Link) pulumi.StringOutput { return v.Target }).(pulumi.StringOutput)
}

func (o LinkOutput) Targets() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Link) pulumi.StringArrayOutput { return v.Targets }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*LinkInput)(nil)).Elem(), &Link{})
	pulumi.RegisterOutputType(LinkOutput{})
}
