// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class Link extends pulumi.CustomResource {
    /**
     * Get an existing Link resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Link {
        return new Link(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'pde:local:Link';

    /**
     * Returns true if the given object is an instance of Link.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Link {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Link.__pulumiType;
    }

    public /*out*/ readonly isDir!: pulumi.Output<boolean>;
    public /*out*/ readonly linked!: pulumi.Output<boolean>;
    public readonly overwrite!: pulumi.Output<boolean | undefined>;
    public readonly recursive!: pulumi.Output<boolean | undefined>;
    public readonly retain!: pulumi.Output<boolean | undefined>;
    public readonly source!: pulumi.Output<string>;
    public readonly target!: pulumi.Output<string>;
    public /*out*/ readonly targets!: pulumi.Output<string[]>;

    /**
     * Create a Link resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: LinkArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.source === undefined) && !opts.urn) {
                throw new Error("Missing required property 'source'");
            }
            if ((!args || args.target === undefined) && !opts.urn) {
                throw new Error("Missing required property 'target'");
            }
            resourceInputs["overwrite"] = args ? args.overwrite : undefined;
            resourceInputs["recursive"] = args ? args.recursive : undefined;
            resourceInputs["retain"] = args ? args.retain : undefined;
            resourceInputs["source"] = args ? args.source : undefined;
            resourceInputs["target"] = args ? args.target : undefined;
            resourceInputs["isDir"] = undefined /*out*/;
            resourceInputs["linked"] = undefined /*out*/;
            resourceInputs["targets"] = undefined /*out*/;
        } else {
            resourceInputs["isDir"] = undefined /*out*/;
            resourceInputs["linked"] = undefined /*out*/;
            resourceInputs["overwrite"] = undefined /*out*/;
            resourceInputs["recursive"] = undefined /*out*/;
            resourceInputs["retain"] = undefined /*out*/;
            resourceInputs["source"] = undefined /*out*/;
            resourceInputs["target"] = undefined /*out*/;
            resourceInputs["targets"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Link.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Link resource.
 */
export interface LinkArgs {
    overwrite?: pulumi.Input<boolean>;
    recursive?: pulumi.Input<boolean>;
    retain?: pulumi.Input<boolean>;
    source: pulumi.Input<string>;
    target: pulumi.Input<string>;
}
