# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_pde.installers as __installers
    installers = __installers
    import pulumi_pde.local as __local
    local = __local
else:
    installers = _utilities.lazy_import('pulumi_pde.installers')
    local = _utilities.lazy_import('pulumi_pde.local')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "pde",
  "mod": "installers",
  "fqn": "pulumi_pde.installers",
  "classes": {
   "pde:installers:GitHubRelease": "GitHubRelease",
   "pde:installers:GitHubRepo": "GitHubRepo"
  }
 },
 {
  "pkg": "pde",
  "mod": "local",
  "fqn": "pulumi_pde.local",
  "classes": {
   "pde:local:File": "File",
   "pde:local:Link": "Link"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "pde",
  "token": "pulumi:providers:pde",
  "fqn": "pulumi_pde",
  "class": "Provider"
 }
]
"""
)
